import type { Metadata } from "next";
import { Fira_Sans, Inter } from "next/font/google";
import "./globals.css";


const fira = Fira_Sans({
  subsets: ["latin"],      // Subconjunto de caracteres que você vai usar
  display: "swap",         // Evita flash de fonte invisível
  weight: ["400", "500", "700"], // Pesos que você vai usar
  variable: "--font-fira", // opcional, para usar como CSS variable
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"], 
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${fira.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
